# Generated by Django 6.0 on 2025-12-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_hours_per_day', models.FloatField()),
                ('extracurricular_hours_per_day', models.FloatField()),
                ('sleep_hours_per_day', models.FloatField()),
                ('social_hours_per_day', models.FloatField()),
                ('physical_activity_hours_per_day', models.FloatField()),
                ('stress_level', models.CharField(max_length=50)),
                ('predicted_gpa', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
