# Generated by Django 6.0 on 2025-12-13 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrecord',
            name='predicted_gpa',
        ),
    ]
